export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_CLEAR_ITEMS = "CART_RESET";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_ORDERNOTES = "CART_SAVE_ORDERNOTES";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_SHIPPING_COST = "CART_SAVE_SHIPPING_COST";
export const CART_SAVE_SHIPPING_TITLE = "CART_SAVE_SHIPPING_TITLE";
export const CART_REMOVE_SHIPPING_RATES = "CART_REMOVE_SHIPPING_RATES";
